"""add vod_streams

Revision ID: 812f05ed097b
Revises: b29c63b4bf54
Create Date: 2026-01-03 04:01:29.354110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812f05ed097b'
down_revision: Union[str, None] = 'b29c63b4bf54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vod_streams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('provider_stream_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=True),
    sa.Column('stream_icon', sa.String(length=800), nullable=True),
    sa.Column('custom_poster_url', sa.String(length=800), nullable=True),
    sa.Column('container_extension', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.String(length=50), nullable=True),
    sa.Column('added', sa.String(length=50), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'provider_stream_id', name='uq_vod_streams_provider_streamid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vod_streams')
    # ### end Alembic commands ###
