"""add custom_logo_url to live_streams

Revision ID: b29c63b4bf54
Revises: e2bed3130843
Create Date: 2026-01-01 19:28:50.259389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29c63b4bf54'
down_revision: Union[str, None] = 'e2bed3130843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'provider_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('epg_programs', 'epg_source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('live_streams', sa.Column('custom_logo_url', sa.String(length=800), nullable=True))
    op.drop_index('ix_live_streams_approved', table_name='live_streams')
    op.drop_index('ix_live_streams_channel_number', table_name='live_streams')
    op.drop_index('uq_live_streams_provider_channel_number', table_name='live_streams', postgresql_where='(channel_number IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_live_streams_provider_channel_number', 'live_streams', ['provider_id', 'channel_number'], unique=True, postgresql_where='(channel_number IS NOT NULL)')
    op.create_index('ix_live_streams_channel_number', 'live_streams', ['channel_number'], unique=False)
    op.create_index('ix_live_streams_approved', 'live_streams', ['approved'], unique=False)
    op.drop_column('live_streams', 'custom_logo_url')
    op.alter_column('epg_programs', 'epg_source_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('categories', 'provider_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
