"""add epg tables

Revision ID: df4a017909cf
Revises: dc5771bd6773
Create Date: 2025-12-31 03:06:11.385171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4a017909cf'
down_revision: Union[str, None] = 'dc5771bd6773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epg_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('xmltv_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('icon_url', sa.String(length=800), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'xmltv_id', name='uq_epg_channels_provider_xmltvid')
    )
    op.create_table('epg_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['epg_channels.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'start_time', name='uq_epg_programs_channel_start')
    )
    op.create_index('ix_epg_programs_channel_time', 'epg_programs', ['channel_id', 'start_time', 'end_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_epg_programs_channel_time', table_name='epg_programs')
    op.drop_table('epg_programs')
    op.drop_table('epg_channels')
    # ### end Alembic commands ###
